@startuml "Home-Cook-Collective-Backend"
!include ../C4_Container.puml

title Backend Container diagram for Home Cook Collective App

System_Ext(frontend, "Frontend", "React Native; TypeScript", "Handles all client-side logic and UI components. Aggregates API calls to the API Gateway.")
System_Ext(google_sso_ext, "Google SSO", "Handles user authentication via Google accounts.")

System_Boundary(backend, "Backend Microservices") {
    Container(api_gateway, "API Gateway", "Express.js", "Single entry point for all backend requests. Handles request routing, authentication (validating OAuth2 tokens - ADR 2), and rate limiting. Aggregates responses from microservices.")
    note right of api_gateway
        Each microservice can use
        internal HTTPS calls to
        communicate with each other (not
        shown for simplicity). For
        **Security** and **Reliability**, the API
        Gateway is the only external
        entrypoint for requests and
        handles rate limiting to prevent
        abuse. This ensures that only
        authenticated users can access
        the backend services and that the
        system can handle high traffic
        without crashing.
    end note

    Container_Boundary(user_microservice, "User Microservice") {
        Container(user_service, "User Service", "Express.js", "Manages user profiles, preferences, authentication-related data, and social features.")
        ContainerDb(user_db, "User Database", "MySQL", "Stores all data related to users from the User Microservice.")
        note right of user_db
            ==Common DB Note==
            Each DB is a Managed MySQL
            service. Configured with
            automated daily backups and
            point-in-time recovery (PITR).
            Target RPO: < 15mins,
            RTO: < 2 hours.
            Read replicas can be added for
            read scalability and HA, balancing
            cost with performance, ensuring
            **Cost Optimization**. Separate
            databases are used for each
            microservice to ensure maximum
            **Reliability** by allowing each
            service to be scaled and if needed,
            recovered independently.
        end note

    }
    Container_Boundary(recipe_microservice, "Recipe Microservice") {
        Container(recipe_service, "Recipe Service", "Express.js ", "Manages recipe creation, discovery, modification, and organization.")
        ContainerDb(recipe_db, "Recipe Database", "MySQL", "Stores all data related to recipes from the Recipe Microservice.")
    }
    Container_Boundary(ingredient_microservice, "Ingredient Microservice") {
        Container(ingredient_service, "Ingredient Service", "Express.js", "Manages ingredients, integrates with USDA API for nutritional data, and caches this data.")
        ContainerDb(ingredient_db, "Ingredient Database", "MySQL", "Stores all data related to ingredients cached from USDA API via Ingredient Microservice.")
        note right of ingredient_db
            To ensure the best **Performance**
            **Efficiency**, ingredients are cached
            up to 30 days. Cached data will be
            more quickly retrieved than from
            the USDA API.
        end note
    }
    Container_Boundary(media_microservice, "Media Microservice") {
        Container(media_service, "Media Service", "Express.js", "Handles media uploads and retrievals.")
        ContainerDb(media_db, "Media Database", "MySQL", "Stores all metadata related to media from the Media Microservice. Media will then be stored in the external Cloud Media Storage.")
    }
}
note right of backend
    To ensure **Cost Optimization** and
    **Reliability**, the backend services
    are split into separately
    deployable microservices so that
    each service can be independently
    scaled to use the minimum
    resources and isolate any faults to
    the responsible microservice.
    Ref: **ADR 5**
end note

System_Ext(usda_api, "USDA API","Provides nutritional information for ingredients.", "fdc.nal.usda.gov")
System_Ext(media_storage_ext, "Cloud Media Storage", "Stores and retrieves user-uploaded media such as recipe images and videos.")

Rel(frontend, api_gateway, "Makes API calls to", "HTTPS")

Rel(api_gateway, user_service, "Routes requests to", "HTTPS")
Rel(api_gateway, recipe_service, "Routes requests to", "HTTPS")
Rel(api_gateway, ingredient_service, "Routes requests to", "HTTPS")
Rel(api_gateway, media_service, "Routes requests to", "HTTPS")

Rel(ingredient_service, usda_api, "Makes API calls to", "HTTPS")
Rel(media_service, media_storage_ext, "Uploads and retrieves media from", "HTTPS")

Rel(user_service, user_db, "Reads from and writes to", "MySQL Protocol")
Rel(recipe_service, recipe_db, "Reads from and writes to", "MySQL Protocol")
Rel(ingredient_service, ingredient_db, "Reads from and writes to", "MySQL Protocol")
Rel(media_service, media_db, "Reads from and writes to", "MySQL Protocol")

Rel(api_gateway, google_sso_ext, "Validates user's token", "OAuth 2.0 / OpenID Connect")

SHOW_LEGEND()
@enduml